debug: false
api:
  host: '0.0.0.0'
  port: 8080
  ssl:
    enabled: false
    cert: ''
    key: ''
  uploads:
  size_limit: 150000000
log:
  path: './logs'
  level: 'info'
  deleteAfterDays: 30
database:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  name: 'mygobb'
  username: 'root'
  password: ''
