[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/lestrrat-go/file-rotatelogs"
  version = "2.1.0"

[[constraint]]
  name = "github.com/rifflock/lfshook"
  version = "2.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"